{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  CENTRAL_SERVER_URL: {{ required "config.centralServerUrl is required" .Values.config.centralServerUrl | quote }}
  CLUSTER_NAME: {{ required "config.clusterName is required" .Values.config.clusterName | quote }}
  AGENT_TOKEN: {{ required "config.agentToken is required" .Values.config.agentToken | quote }}
{{- end }}
